#cloud-config
groups:
  - riscv: [root]

runcmd:
  - [bash, -c, "yum install -y devtoolset-11 rh-git227 rh-python38"]
  - [bash, -c, "echo source /opt/rh/devtoolset-11/enable >> /etc/profile.d/devtoolset-11.sh"]
  - [bash, -c, "echo source /opt/rh/rh-python38/enable >> /etc/profile.d/rh-python38.sh"]
  - [bash, -c, "echo source /opt/rh/rh-git227/enable >> /etc/profile.d/rh-git227.sh"]
  - [bash, -c, "mkdir -p /srv/riscv/bin"]
  - [bash, -ilxc, "git clone https://github.com/riscv/riscv-gnu-toolchain /srv/riscv/src"]
  - [bash, -xc, "chown -R centos:riscv /srv/riscv"]
  - [bash, -xc, "chmod -R g+rwX /srv/riscv"]
  - [su, -, centos, -c, "/srv/riscv/src/configure --prefix=/srv/riscv --enable-multilib"]
  - [su, -, centos, -c, "make linux"]

users:
  - default
  - name: cva6
#    This allows you to import your public keys from your GitHub user
#    if you use the prefix gh or from another keyserver
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, riscv
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKn0TsJ+v46lLs9XmoQ25BCqhx/arF1Td/BvjN6NBip
    lock_passwd: false

package_upgrade: true

packages:
  - curl
  - tmux
  - podman
  - vim-enhanced
  - texinfo
  - zlib-devel
  - expat-devel
  - libslirp-devel
  - autoconf
  - automake
  - libmpc-devel
  - mpfr-devel
  - gmp-devel
  - gawk
  - bison
  - flex
  - texinfo
  - patchutils
  - centos-release-scl
  - centos-release-scl-rh
